services:
  mongodb:
    image: mongo
    container_name: mongodb-healthtracker
    restart: always
    environment:
      - MONGO_INITDB_DATABASE = healthtracker
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis-healthtracker
    restart: always
    ports:
      - "6379:6379"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthtracker
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
volumes:
  mongodb_data:
